name: i3_meetings
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  dio: ^4.0.4
  googleapis: ^8.0.0
  googleapis_auth: ^1.3.0
  i3_block_sdk:
    path: '../i3_block_sdk'
  path: ^1.8.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
