name: i3_toggl
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  args: ^2.3.0
  dio: ^4.0.4
  i3_block_sdk:
    path: '../i3_block_sdk'
  path: ^1.8.1

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
